### ISSUE TITLE
Export Log

### ISSUE THREAD

**Issue by Cuphat** [deains/racetime-app#26]
I think it'd be nice to be able to export a chat and event log text file for local preservation. When racing on SRL I like to keep my chat logs for historical purposes and it makes me sad that I can't really do that on racetime.

**Comment by deains** [comment]
Hiya @Cuphat, this already exists. 😁 Type `.log` in the chat to get a download link, or just add `/log` to the URL of any race room to download directly. Example: https://racetime.gg/ootr/adequate-hitbox-7111/log

**Comment by Cuphat** [comment]
lmao welp, I didn't think . commands were a thing here, thanks for that.
